version: '3.4'

services:
  db:
    image: postgres:16.2
    env_file:
      - .env

  sync-web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/opt/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  async-web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/opt/code
    ports:
      - "8001:8001"
    depends_on:
      - db
    command: uvicorn main:app --reload --port 8001
