version: '3.4'

services:
  db:
    image: postgres
    env_file:
      - .env

  api:
    build: .
    env_file:
      - .env
    volumes:
      - .:/opt/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: bash ./scripts/runserver.sh
