version: '3.4'

services:
  db:
    image: postgres
    env_file:
      - .env

  api:
    build:
      context: ..
      dockerfile: ./prod/Dockerfile
    env_file:
      - .env
    volumes:
      - static_volume:/opt/code/static
      - shm:/dev/shm
    depends_on:
      - db
    command: bash ./scripts/run-with-gunicorn.sh 2

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - static_volume:/opt/code/static
      - shm:/dev/shm
    depends_on:
      - api

volumes:
  static_volume:
  shm:
